Repository inspirehep/inspirehep-search-js, pull requests merged in 2018-03, with the labels that each got.

#66 link DOIs against preferred resolver
  src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/details/details.html
  src/inspirehep-search-js/filters/doi.js
  src/inspirehep-search-js/filters/publicationInfoDoi.js
  test/unit/filters/filterDoiSpec.js
  test/unit/filters/filterPublicationInfoDoiSpec.js
Labels: Review: WIP

#70 add editor btn back to results page
  src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/results/results.html
Labels: Review: WIP

#71 holdingpen: add crawl_errors ui
  src/inspirehep-holdingpen-js/holdingpen/holdingpen.controllers.js
  src/inspirehep-holdingpen-js/holdingpen/holdingpen.directives.js
  src/inspirehep-holdingpen-js/holdingpen/holdingpen.services.js
  src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/details/details.html
  src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/details/details_errors.html
  src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/results/results_details_hep.html
Labels: Review: Ready for Review

#72 holdingpen: fix results view match message
  src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/results/results.html
Labels: Review: Ready for Review

#73 holdingpen: add keyword source
  src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/details/details_decision_hep.html
  src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/results/results.html
Labels: Review: In Review

#74 holdingpen: fix 'View Stack Trace' duplication
  src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/details/details.html
Labels: Review: Ready for Review

#75 holdingpen: group match radios for each record
  src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/results/results.html
Labels: Review: WIP

#77 holdingpen: make fuzzy match ui more compact
  src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/results/results.html
Labels: Review: WIP
